version: 2.1
defaults: &defaults
  docker:
    - image: circleci/python:3.7.5

jobs:
  unit_tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Lint
          command: |
            . venv/bin/activate
            mkdir -p test-reports
            pycodestyle sample | tee test-reports/pycodestyle.log

      - run:
          name: Unit Tests
          command: |
            . venv/bin/activate
            mkdir -p test-reports
            coverage run -a --omit=lib venv/bin/nose2 -c unittest.cfg

      - run:
          name: XML Coverage Report
          command: |
            . venv/bin/activate
            coverage xml

      - run:
          name: Upload report to Codecov
          command: |
            . venv/bin/activate
            codecov --file=test-reports/coverage.xml --token=$CODECOV_TOKEN

      - store_artifacts:
          path: test-reports
          destination: test-reports
workflows:
  version: 2
  commit:
    jobs:
      - unit_tests
